export const FETCH_PIZZAS = "FETCH_PIZZAS";
export const ADD_TO_CART = "ADD_TO_CART";
export const CART_UPDATE = "CART_UPDATE";

export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PLACE_ORDER = "PLACE_ORDER";
